version: "3.8"

services:
  lattice_pserve:
    image: lattice_pserve
    container_name: lattice-pserve
    ports:
      - 6543:6543
    environment:
      LATTICE_INI: development-docker.ini
    volumes:
      - ./:/app
    networks:
      - latticed
    depends_on:
      lattice_dev_servers:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
      target: pserve

  lattice_dev_servers:
    image: lattice_dev_servers
    container_name: lattice-dev-servers
    ports:
      - 5432:5432
      - 9201:9201
    environment:
      LATTICE_INI: development-docker.ini
    volumes:
      - ./:/app
    networks:
      - latticed
    healthcheck:
      test: ['CMD', 'curl', 'localhost:9201']
      interval: 5s
      timeout: 5s
      retries: 3
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev_servers

networks:
  latticed:
    driver: bridge
